- name: Create User
  hosts: all
  become: true
  vars_files:
    - quiz-Secret.yml
  tasks:
    - name: Create User
      user:
        name: "{{username}}"
        password: "{{passwd | password_hash('sha512')}}"